name: Generate JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust version as needed

      # Step 3: Install dependencies and run the JavaScript file
      - name: Install Dependencies and Run Script
        run: |
          npm ci
          node algorithms/gen-json.cjs # Replace with the name of your JS file

      # Step 4: Commit and push changes
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add algorithms/algorithms.json
          git commit -m "Update algorithms.json from GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/WombleWoo7547/problemsolving.git
